<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/sum.proto

namespace Sum;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>sum.ServerInfo</code>
 */
class ServerInfo extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string version = 1;</code>
     */
    private $version = '';
    /**
     * Generated from protobuf field <code>uint64 uptime = 2;</code>
     */
    private $uptime = 0;
    /**
     * Generated from protobuf field <code>uint64 pid = 3;</code>
     */
    private $pid = 0;
    /**
     * Generated from protobuf field <code>uint64 uid = 4;</code>
     */
    private $uid = 0;
    /**
     * Generated from protobuf field <code>repeated string argv = 5;</code>
     */
    private $argv;
    /**
     * Generated from protobuf field <code>uint64 records = 6;</code>
     */
    private $records = 0;
    /**
     * Generated from protobuf field <code>uint64 oracles = 7;</code>
     */
    private $oracles = 0;

    public function __construct() {
        \GPBMetadata\Proto\Sum::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>string version = 1;</code>
     * @return string
     */
    public function getVersion()
    {
        return $this->version;
    }

    /**
     * Generated from protobuf field <code>string version = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setVersion($var)
    {
        GPBUtil::checkString($var, True);
        $this->version = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 uptime = 2;</code>
     * @return int|string
     */
    public function getUptime()
    {
        return $this->uptime;
    }

    /**
     * Generated from protobuf field <code>uint64 uptime = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setUptime($var)
    {
        GPBUtil::checkUint64($var);
        $this->uptime = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 pid = 3;</code>
     * @return int|string
     */
    public function getPid()
    {
        return $this->pid;
    }

    /**
     * Generated from protobuf field <code>uint64 pid = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setPid($var)
    {
        GPBUtil::checkUint64($var);
        $this->pid = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 uid = 4;</code>
     * @return int|string
     */
    public function getUid()
    {
        return $this->uid;
    }

    /**
     * Generated from protobuf field <code>uint64 uid = 4;</code>
     * @param int|string $var
     * @return $this
     */
    public function setUid($var)
    {
        GPBUtil::checkUint64($var);
        $this->uid = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated string argv = 5;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getArgv()
    {
        return $this->argv;
    }

    /**
     * Generated from protobuf field <code>repeated string argv = 5;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setArgv($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->argv = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 records = 6;</code>
     * @return int|string
     */
    public function getRecords()
    {
        return $this->records;
    }

    /**
     * Generated from protobuf field <code>uint64 records = 6;</code>
     * @param int|string $var
     * @return $this
     */
    public function setRecords($var)
    {
        GPBUtil::checkUint64($var);
        $this->records = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 oracles = 7;</code>
     * @return int|string
     */
    public function getOracles()
    {
        return $this->oracles;
    }

    /**
     * Generated from protobuf field <code>uint64 oracles = 7;</code>
     * @param int|string $var
     * @return $this
     */
    public function setOracles($var)
    {
        GPBUtil::checkUint64($var);
        $this->oracles = $var;

        return $this;
    }

}

