# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from proto import sum_pb2 as proto_dot_sum__pb2


class SumServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.CreateRecord = channel.unary_unary(
        '/sum.SumService/CreateRecord',
        request_serializer=proto_dot_sum__pb2.Record.SerializeToString,
        response_deserializer=proto_dot_sum__pb2.RecordResponse.FromString,
        )
    self.UpdateRecord = channel.unary_unary(
        '/sum.SumService/UpdateRecord',
        request_serializer=proto_dot_sum__pb2.Record.SerializeToString,
        response_deserializer=proto_dot_sum__pb2.RecordResponse.FromString,
        )
    self.ReadRecord = channel.unary_unary(
        '/sum.SumService/ReadRecord',
        request_serializer=proto_dot_sum__pb2.ById.SerializeToString,
        response_deserializer=proto_dot_sum__pb2.RecordResponse.FromString,
        )
    self.DeleteRecord = channel.unary_unary(
        '/sum.SumService/DeleteRecord',
        request_serializer=proto_dot_sum__pb2.ById.SerializeToString,
        response_deserializer=proto_dot_sum__pb2.RecordResponse.FromString,
        )
    self.Info = channel.unary_unary(
        '/sum.SumService/Info',
        request_serializer=proto_dot_sum__pb2.Empty.SerializeToString,
        response_deserializer=proto_dot_sum__pb2.ServerInfo.FromString,
        )


class SumServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def CreateRecord(self, request, context):
    """vectors CRUD
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def UpdateRecord(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ReadRecord(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def DeleteRecord(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Info(self, request, context):
    """oracles CRUD
    rpc CreateOrace(Oracle) returns

    core methods
    TODO: rpc Eval(EvalRequest) (???) {}
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_SumServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'CreateRecord': grpc.unary_unary_rpc_method_handler(
          servicer.CreateRecord,
          request_deserializer=proto_dot_sum__pb2.Record.FromString,
          response_serializer=proto_dot_sum__pb2.RecordResponse.SerializeToString,
      ),
      'UpdateRecord': grpc.unary_unary_rpc_method_handler(
          servicer.UpdateRecord,
          request_deserializer=proto_dot_sum__pb2.Record.FromString,
          response_serializer=proto_dot_sum__pb2.RecordResponse.SerializeToString,
      ),
      'ReadRecord': grpc.unary_unary_rpc_method_handler(
          servicer.ReadRecord,
          request_deserializer=proto_dot_sum__pb2.ById.FromString,
          response_serializer=proto_dot_sum__pb2.RecordResponse.SerializeToString,
      ),
      'DeleteRecord': grpc.unary_unary_rpc_method_handler(
          servicer.DeleteRecord,
          request_deserializer=proto_dot_sum__pb2.ById.FromString,
          response_serializer=proto_dot_sum__pb2.RecordResponse.SerializeToString,
      ),
      'Info': grpc.unary_unary_rpc_method_handler(
          servicer.Info,
          request_deserializer=proto_dot_sum__pb2.Empty.FromString,
          response_serializer=proto_dot_sum__pb2.ServerInfo.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'sum.SumService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
